- name: Install required packages for Keystone
  apt:
    name:
      - keystone
      - apache2
      - libapache2-mod-wsgi-py3
      - python3-pip
    state: present
- name: Install Keystone packages
  apt:
    name: keystone
    state: present

- name: Enable and start Keystone service
  systemd:
    name: apache2
    state: started
    enabled: yes

- name: Start Apache server
  systemd:
    name: apache2
    state: started
    enabled: yes
