---
- name: Install required packages for Glance
  apt:
    name:
      - glance
      - apache2
      - libapache2-mod-wsgi-py3
      - python3-pip
    state: present

- name: Install Glance packages
  apt:
    name: glance
    state: present

- name: Enable and start Glance API service
  systemd:
    name: glance-api
    state: started
    enabled: yes
